_target_: src.models.dqn_model.DQNLightning

env: Pong-v0
replay_size: 100000
warm_start_steps: 10000
gamma: 0.99
eps_start: 1.0
eps_end: 0.02
eps_last_frame: 150000
sync_rate: 1000
lr: 1e-4
episode_length: 500
batch_size: 64
seed: 123