_target_: src.models.dqn_model.DQNLightning

input_size: 784
lin1_size: 256
lin2_size: 256
lin3_size: 256
output_size: 10
lr: 0.001
weight_decay: 0.0005

env: "CartPole-v1"
replay_size: 1000
warm_start_steps: 1000
gamma: 0.99
eps_start: 1.0
eps_end: 0.01
eps_last_frame: 1000
sync_rate: 10
lr: 1e-2
episode_length: 200
batch_size: 16